//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class SlotsView
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string PlaceName { get; set; }
        [DataMember]
        public Nullable<int> PlaceId { get; set; }
        [DataMember]
        public int FreeSlots { get; set; }
    }
}
